add histogram
js-tasks-ru/htmlcss-20220120_sofia8 pull request #10
Opened 2022-02-10 09:48 UTC by sofiasherbakova

2022-02-10 09:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-11 10:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-12 12:49 UTC, GSemikozov requested changes

2022-02-12 12:49 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__title_color_grey {
для .histogram__title_color_grey и .histogram__title_color_blue лучше задать какие-то более емкие по смыслу классы, например .histogram__title +.histogram__link

2022-02-12 13:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-12 13:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-12 14:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-16 21:28 UTC, GSemikozov approved these changes

2022-02-16 21:28 UTC, merged