button
js-tasks-ru/htmlcss-20220120_sofia8 pull request #3
Opened 2022-01-27 18:21 UTC by sofiasherbakova

2022-01-27 18:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-27 22:22 UTC, GSemikozov requested changes

2022-01-27 22:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_common {
предлагаю заменить .button_common на .button - поскольку именно в блоке описываем основные стили, а в модификаторе - нечто особенное / модифицируемое

2022-01-27 22:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-style: normal;
не хватает font-family)

2022-01-27 22:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: white;
цвет лучше не хардкодить

2022-01-27 22:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    color: white;
и избегать именованных цветов (лучше hex)

2022-01-27 22:22 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.wrapper {
wrapper + title - это отдельные вспомогательные стили, которые не относятся к компоненту Кнопка. В файле стилей компонента должны быть стили только для этого компонента + его элементов и модификаторов)
вспомогательные стили если мы их нигде больше не переиспользуем лучше выносить сразу на хтмл страницу с решением в тег style

2022-01-31 09:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-02 22:24 UTC, GSemikozov approved these changes

2022-02-02 22:25 UTC, merged