add skeleton
js-tasks-ru/htmlcss-20220120_sofia8 pull request #7
Opened 2022-02-09 12:44 UTC by sofiasherbakova

2022-02-09 12:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-12 12:45 UTC, GSemikozov requested changes

2022-02-12 12:45 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__line_width_40, .skeleton__line_width_60, .skeleton__line_width_100{
модификаторы отдельно от их блоков. / элементов использовать нельзя (они просто указывают на то, что и как модифицируем у имеющегося блока / элемента). Поэтому - в хтмл на один уровень с этими модификаторами надо добавить общий класс - классс элемента - .skeleton__line,  а в css конкретно в этой строке мы просто вместо всех перечисленных модификаторов укажем .skeleton__line (это то общее, что будет у всех линий).

2022-02-16 21:26 UTC, GSemikozov approved these changes

2022-02-16 21:26 UTC, merged