add cards
js-tasks-ru/htmlcss-20220120_sofia8 pull request #9
Opened 2022-02-09 20:09 UTC by sofiasherbakova

2022-02-09 20:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-12 12:47 UTC, GSemikozov requested changes

2022-02-12 12:47 UTC, GSemikozov commented on components/card/card.css
> +.card__top {
при таком подходе тайтлы в разных карточках будут не на одном уровне (в .card__top будут блоки разной высоты). Чтобы все было красиво, надо прижать тайтлы к низу карточки, что достигается простым добавляем здесь flex-grow: 1 )

2022-02-16 21:28 UTC, GSemikozov requested changes

2022-02-16 21:28 UTC, GSemikozov commented on components/card/card.css
> +    min-height: 224px;
вот это лишнее.
а display: flex и пр. надо задать .card, иначе flex-grow работать не будет)

2022-02-18 10:04 UTC, GSemikozov approved these changes

2022-02-18 10:04 UTC, merged